# https://pre-commit.com/
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-vcs-permalinks
      - id: check-added-large-files
  # Commitizen
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.26.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
  # Python
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^.*/tests/.*\.py$
